App\Entity\User:
    type: entity
    table: users
    repositoryClass: App\Repository\UserRepository
    id:
        id:
            type: uuid
    fields:
        email:
            type: string
            scale: 0
            length: 512
            unique: true
            nullable: false
            precision: 0
        password:
            type: string
            scale: 0
            length: 512
            unique: false
            nullable: false
            precision: 0
        roles:
            type: json
            scale: null
            length: null
            unique: false
            nullable: false
            precision: null
        isActive:
            type: boolean
            scale: null
            length: null
            unique: false
            nullable: false
            precision: null
            column: is_active
        createdAt:
            type: datetime
            scale: null
            length: null
            unique: false
            nullable: false
            precision: null
            column: created_at
        updatedAt:
            type: datetime
            scale: null
            length: null
            unique: false
            nullable: true
            precision: null
            column: updated_at