version: '3'

services:
    db:
        image: mysql:8.0.21
        command: --default-authentication-plugin=mysql_native_password
        volumes:
            - "db_librarify:/var/lib/mysql"
        environment:
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
            MYSQL_DATABASE: ${MYSQL_DATABASE}
            MYSQL_USER: ${MYSQL_USER}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD}
        ports:
            - 3306:3306
        networks:
            - symfony
    php:
        build:
            context: .
            dockerfile: docker/php/Dockerfile
            args:
                TIMEZONE: ${TIMEZONE}
        volumes:
            - ./librarify/:/var/www/librarify/
        networks:
            - symfony
    nginx:
        build:
            context: .
            dockerfile: docker/nginx/Dockerfile
        volumes:
            - ./librarify/:/var/www/librarify/
        ports:
            - 80:80
        networks:
            - symfony

volumes:
    db_librarify:

networks:
    symfony: