App\Form\Model\Author:
    properties:
        name:
            - NotBlank: ~
            - Length:
                min: 3
                max: 100
                minMessage: 'The title must be at least {{ limit }} characters long'
                maxMessage: 'The title cannot be longer than {{ limit }} characters'
                #allowEmptyString: false deprecaded since sf 5.2