App\Entity\Author:
    type: entity
    table: authors
    repositoryClass: App\Repository\AuthorRepository
    id:
        id:
            type: uuid
        
    fields:
        name:
            type: string
            scale: null
            length: 255
            unique: false
            nullable: false
            precision: null
    manyToMany:
        books:
            targetEntity: App\Entity\Book
            cascade: {  }
            fetch: LAZY
            mappedBy: authors
            inversedBy: null
            joinTable: {  }
            orderBy: null
    lifecycleCallbacks: {  }
