version: '3.5'

services:
  symfony-api-rest-db:
    container_name: symfony-api-rest-db
    image: mysql:8.0
    ports:
      - 36000:3306
    environment:
      MYSQL_DATABASE: librarify
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root
    command: mysqld --sql_mode="STRICT_ALL_TABLES,NO_ENGINE_SUBSTITUTION"
    volumes:
      - symfony-api-rest-db-data:/var/lib/mysql
    networks:
      - symfony-api-rest-network

  symfony-api-rest-web:
    container_name: symfony-api-rest-web
    build:
      context: ./docker/nginx
      args:
        UID: $U_ID
    ports:
      - 250:80
    volumes:
      - ./public:/appdata/www/public
    depends_on:
      - symfony-api-rest-be
    networks:
      - symfony-api-rest-network
  
  symfony-api-rest-be:
    container_name: symfony-api-rest-be
    build:
      context: docker/php
      args:
        UID: $U_ID
    environment:
      PHP_IDE_CONFIG: serverName=Docker
      PHP_XDEBUG_ENABLED: 1
      XDEBUG_CONFIG: remote_host=172.17.0.1 remote_port=9005 # Linux users
    #      XDEBUG_CONFIG: remote_host=host.docker.internal remote_port=9005 # MacOS users
    volumes:
      - ./:/appdata/www
      - ./docker/php/xdebug-linux.ini:/usr/local/etc/php/conf.d/xdebug.ini
      #      - ./docker/php/xdebug-macos.ini:/usr/local/etc/php/conf.d/xdebug.ini
      - ~/.ssh/id_rsa:/home/appuser/.ssh/id_rsa
    depends_on:
      - symfony-api-rest-db
    networks:
      - symfony-api-rest-network

  symfony-api-rest-phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: symfony-api-rest-phpmyadmin
    networks:
      - symfony-api-rest-network
    ports:
      - "251:80"
    environment:
      # arbitrary server option - allowing you to specify any MySQL/MariaDB server on the login page
      #- PMA_ARBITRARY=1
      - PMA_HOST=symfony-api-rest-db
      - PMA_USER=root
      - PMA_PASSWORD=root
    depends_on:
      - symfony-api-rest-db

volumes:
  symfony-api-rest-db-data:

networks:
  symfony-api-rest-network:
    external: true
